---
title: "RNA-seq analysis in R"
subtitle: "Pre-processsing RNA-seq data - solutions"
author: "Stephane Ballereau, Dominique-Laurent Couturier, Mark Dunning, Abbi Edwards, Ashley Sawle"
date: '`r format(Sys.time(), "Last modified: %d %b %Y")`'
output:
  html_document:
    toc: yes
    toc_float: yes
layout: page
---

### Data 

```{r setup, message = FALSE}
library(tximport)
library(DESeq2)
library(tidyverse)
```

```{r prepareData, message=FALSE, include=FALSE}
# This chunk is just for the knitting
# Read the sample information into R
sampleinfo <- read_tsv("data/samplesheet.tsv", col_types = c("cccc")) %>% 
  arrange(Group, TimePoint, Replicate)
# Read the data into R
txi <- readRDS("RObjects/txi.rds")
rawCounts <- round(txi$counts, 0)
# filter
keep <- rowSums(rawCounts) > 5
filtCounts <- rawCounts[keep,]
# VST
vst_counts <- vst(filtCounts)
groupCols <- str_replace_all(sampleinfo$Group, c(Test="red", Control="orange"))
```

### Challenge 1
>
> 1. Use the `DESeq2` function `rlog` to transform the count data. This function
> also normalises for library size.
> 2. Plot the count distribution boxplots with this data.
> How has this effected the count distributions?

```{r, message=FALSE}
rlogcounts <- rlog(filtCounts)

# Check distributions of samples using boxplots
boxplot(rlogcounts, 
        xlab="", 
        ylab="Log2(Counts)",
        las=2,
        col=groupCols)
# Let's add a blue horizontal line that corresponds to the median logCPM
abline(h=median(as.matrix(rlogcounts)), col="blue")
```
